### ISSUE TITLE
konduit serve -id simple_test -c ./simple.yaml  show some error

### ISSUE THREAD

**Issue by wangfeng-skymind** [KonduitAI/konduit-serving-examples#27]
[root@iZ2ze3hiduvxw3kac9o07jZ yaml]# konduit serve -id simple_test -c ./simple.yaml 
Starting konduit server...
INFO: Running command /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.x86_64/jre/bin/java -Djava.awt.headless=true -jar /root/.konduit-serving/jar/konduit.jar run --instances 1 -s inference -c ./simple.yaml -Dserving.id=simple_test
Processing configuration: /home/konduit-serving-examples/yaml/./simple.yaml
Starting konduit server with an id of 'simple_test'
11:53:03.525 [main] INFO  ai.konduit.serving.util.LogUtils - Logging file at: /root/.konduit-serving/command_logs/simple_test.log
11:53:03.663 [main] ERROR a.k.s.l.command.KonduitRunCommand - Configuration file serving:
  http_port: 1337
  input_data_format: NUMPY
  output_data_format: NUMPY
  log_timings: True
  extra_start_args: -Xmx8g
steps:
  python_step:
    type: PYTHON
    python_code: |
      first += 2
      second = first
    python_inputs:
      first: NDARRAY
    python_outputs:
      second: NDARRAY
client:
    port: 1337 does not contain a valid JSON object
11:53:03.688 [main] INFO  a.k.s.l.KonduitServingLauncher - Setup micro meter options.
11:53:04.080 [vert.x-eventloop-thread-0] INFO  a.k.s.routers.PipelineRouteDefiner - Using metrics registry io.micrometer.prometheus.PrometheusMeterRegistry for inference
11:53:04.093 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable - java.lang.NullPointerException
11:53:04.094 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.routers.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:161)
11:53:04.094 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.verticles.inference.InferenceVerticle.setupWebServer(InferenceVerticle.java:87)
11:53:04.094 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.verticles.base.BaseRoutableVerticle.start(BaseRoutableVerticle.java:87)
11:53:04.094 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
11:53:04.094 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
11:53:04.094 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
11:53:04.094 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
11:53:04.094 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
11:53:04.094 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
11:53:04.095 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
11:53:04.095 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
11:53:04.095 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
11:53:04.095 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at java.lang.Thread.run(Thread.java:748)
11:53:04.096 [vert.x-eventloop-thread-1] ERROR i.v.c.i.l.c.VertxIsolatedDeployer - Failed in deploying verticle
java.lang.NullPointerException: null
        at ai.konduit.serving.routers.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:161)
        at ai.konduit.serving.verticles.inference.InferenceVerticle.setupWebServer(InferenceVerticle.java:87)
        at ai.konduit.serving.verticles.base.BaseRoutableVerticle.start(BaseRoutableVerticle.java:87)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
11:53:04.097 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable - java.lang.NullPointerException
11:53:04.097 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.routers.PipelineRouteDefiner.defineRoutes(PipelineRouteDefiner.java:161)
11:53:04.097 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.verticles.inference.InferenceVerticle.setupWebServer(InferenceVerticle.java:87)
11:53:04.097 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at ai.konduit.serving.verticles.base.BaseRoutableVerticle.start(BaseRoutableVerticle.java:87)
11:53:04.097 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
11:53:04.097 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
11:53:04.097 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
11:53:04.097 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
11:53:04.098 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
11:53:04.098 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
11:53:04.098 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
11:53:04.098 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
11:53:04.098 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
11:53:04.098 [vert.x-eventloop-thread-1] ERROR java.lang.Throwable -    at java.lang.Thread.run(Thread.java:748)
11:53:04.098 [vert.x-eventloop-thread-1] ERROR a.k.s.l.KonduitServingLauncher - 
Failed to start konduit server

**Comment by wangfeng-skymind** [comment]
@saudet  what causes this error?

**Comment by saudet** [comment]
I don't know. It looks like an error in the YAML config file, but I'm not familiar with this.
@AlexDBlack ? @farizrahman4u ?

**Comment by ShamsUlAzeem** [comment]
Yup old yaml format. I'll update the examples

**Comment by ShamsUlAzeem** [comment]
@wangfeng-skymind I've updated the examples so you should be able to run with the yaml config files.

**Comment by ShamsUlAzeem** [comment]
Can you confirm if it's working for you now?

**Comment by wangfeng-skymind** [comment]
@ShamsUlAzeem ya, now is normal after update these examples
